package ftn.sbzn.PoEhelperbackend.model;

public enum WeaponType {
    WAND, ONE_HAND_MACE, ONE_HAND_SWORD, ONE_HAND_AXE, STAFF, TWO_HAND_MACE, TWO_HAND_SWORD, TWO_HAND_AXE, SCEPTER, DAGGER, BOW_AND_QUIVER, SHIELD
}
